# Generated by Django 2.2.1 on 2019-06-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro_post.Post'),
        ),
    ]
